# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build the application to submit the QA Scheme to TestFlight"
  lane :qaBuild do
    get_certificates
    get_provisioning_profile
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "Runner.xcodeproj"
    )
    gym(
      scheme: "dev"
    )
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "Runner.xcodeproj"
    )
    upload_to_testflight
    clean_build_artifacts
  end
end