# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build the application to submit the QA Scheme to TestFlight"
  lane :uatBuild do
    get_certificates
    get_provisioning_profile
    enable_automatic_code_signing
    gym(
      scheme: "stage"
    )
    upload_to_testflight
    clean_build_artifacts
    commit_version_bump(
      message: "👷 Pushed new build on TestFlight (build #{lane_context[SharedValues::BUILD_NUMBER]}) [skip ci]",
      xcodeproj: 'Runner.xcodeproj'
    )
  end
end