variables:
  PROJECT_NAME: gogopharma
  DEV_APP_VARIANT: dev
  QA_APP_VARIANT: dev
  STAGING_APP_VARIANT: stage
  PROD_APP_VARIANT: prod
  APP_BUILD_TYPE_DEBUG: debug
  APP_BUILD_TYPE_RELEASE: release
  APP_VERSION: 2.2.7
  SONAR_TOKEN: "c224777e27b45bbdb50c2bd83c60dba27ed75edc"
  SONAR_HOST_URL: "https://devops.webandcrafts.in/"
  SONAR_PROJECT_KEY: ""
  SONAR_PROJECT_NAME: ""
  FIREBASE_DEV_APP_ID: "1:412008018175:android:03b96b90d12177a7769cca"
  FIREBASE_QA_APP_ID: "1:412008018175:android:03b96b90d12177a7769cca"
  FIREBASE_STAGE_APP_ID: "1:412008018175:android:6dbb484c157fa63a769cca"
  FIREBASE_PROD_APP_ID: "1:412008018175:android:6af2b80fe21126d1769cca"
  FIREBASE_WAC_QA_GROUP: "wac_testers"
  FIREBASE_CI_TOKEN: "1//0g4_ykgFAxJGXCgYIARAAGBASNwF-L9Iry4wRqD0e5X51_ObAh2yeMT52i1tg164WOslXjsqrxJdVo9h9dWRsb3nRyBhbHVusOkk"
  MANAGER_EMAILS: "binu@webandcrafts.com"
  QA_EMAILS: "febin@wacmob.com"